FROM rust:1.66.0

RUN apt-get update

RUN apt-get install -y --no-install-recommends \
    libavutil-dev libavformat-dev libavfilter-dev libavdevice-dev libclang-dev

ARG USER=1000:1000

RUN mkdir /rust && chown $USER /rust

USER $USER

ENV HOME=/rust

WORKDIR /code

COPY --from=mwader/static-ffmpeg:5.0.1-3 /ffmpeg /usr/local/bin/
COPY --from=mwader/static-ffmpeg:5.0.1-3 /ffprobe /usr/local/bin/
